# Configuration template for iceaggr
# Copy this file to config.yaml and update paths for your system
# cp config.template.yaml config.yaml

# Data paths
data:
  # Root directory containing IceCube Kaggle data
  root: /path/to/icecube_kaggle

  # Training data directory
  train: /path/to/icecube_kaggle/train

  # Test data directory
  test: /path/to/icecube_kaggle/test

  # Optional: specify batch file pattern
  batch_pattern: "batch_*.parquet"

# Model configuration
model:
  # DOM-level transformer (T1)
  dom_transformer:
    d_model: 128
    nhead: 8
    num_layers: 4

  # Event-level transformer (T2)
  event_transformer:
    d_model: 256
    nhead: 8
    num_layers: 6

# Training configuration
training:
  batch_size: 32
  learning_rate: 1e-4
  num_epochs: 100

  # Device
  device: cuda  # or 'cpu'

  # Mixed precision
  use_amp: true

# Logging
logging:
  # Weights & Biases
  use_wandb: true
  wandb_project: iceaggr
  wandb_entity: null  # Set to your W&B username or team

  # Local logging
  log_dir: logs
  checkpoint_dir: checkpoints
